
development:
  adapter: postgresql
  database: TDList_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: TDList_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: TDList_test
  pool: 5
  timeout: 5000
